### ISSUE TITLE
rspec fails on XActivatePowerMode

### ISSUE THREAD

**Issue by mralexgray** [alcatraz/alcatraz-packages#435]
`rspec` is choking on (the valid) Image URL https://camo.githubusercontent.com/a25916ccc96abf4f949ae55a3fc8b0108ac578a8/687474703a2f2f3764396f30782e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f584163746976617465506f7765724d6f6465707265766965772e676966  simply because it doesn't "end with" an image extension as defied in the spec.

```
......F

Failures:

  1) Packages should have valid URLs for screenshots if they are present
     Failure/Error: valid_image_formats.should include package['screenshot'].split('.').last
       expected ["png", "jpg", "jpeg", "bmp", "gif"] to include "com/a25916ccc96abf4f949ae55a3fc8b0108ac578a8/687474703a2f2f3764396f30782e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f584163746976617465506f7765724d6f6465707265766965772e676966"
     # ./spec/packages_spec.rb:55:in `block (3 levels) in <top (required)>'
     # ./spec/packages_spec.rb:53:in `each'
     # ./spec/packages_spec.rb:53:in `block (2 levels) in <top (required)>'

Finished in 0.11198 seconds (files took 0.22889 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/packages_spec.rb:51 # Packages should have valid URLs for screenshots if they are present
```

![Image](https://camo.githubusercontent.com/a25916ccc96abf4f949ae55a3fc8b0108ac578a8/687474703a2f2f3764396f30782e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f584163746976617465506f7765724d6f6465707265766965772e676966)

**Comment by jurre** [comment]
I'm open to suggestions on how to improve the spec

**Comment by mralexgray** [comment]
i wish I knew more about `specs`
